FROM ros:lyrical

# Install demo nodes + rmw_zenoh from ROS binary packages.
RUN apt-get update && apt-get install -y \
    ros-lyrical-demo-nodes-cpp \
    ros-lyrical-rmw-zenoh-cpp \
    && rm -rf /var/lib/apt/lists/*

COPY zenoh_session.json5 /config/zenoh_session.json5

COPY ros2_entrypoint.sh /ros2_entrypoint.sh
RUN chmod +x /ros2_entrypoint.sh
ENTRYPOINT ["/ros2_entrypoint.sh"]
